### ISSUE TITLE
provided formatted lists for server

### ISSUE THREAD

**Issue by arlin** [phylotastic/Phylotastic_WebService_Projects#5]
After the list schema is implemented, the next step is to populate it with list data.  Use information from species lists to create tables with the data for each list.  Begin by focusing on a small set of lists that we want to use in phylotastic-portal for testing.

**Comment by abusalehmdtayeen** [comment]
Formatted list for species list server has to follow the method described in https://github.com/phylotastic/Phylotastic_WebService_Documentation/blob/master/SpeciesListServer/SpeciesListArchiveGuide.md

I created this document by following the Darwin Core Archive. In general use case a user will be uploading one list at a time. For each list there will be multiple required or optional files in the archive file.

I will modify the document to reflect the change in the schema.

**Comment by hdliv** [comment]
Abu.  Are the lists I sent over OK?

**Comment by abusalehmdtayeen** [comment]
Dail, I was trying to parse one of your formatted list. But I found that you have used comma inside the value of some fields. For example, in study1 list for List Author field you have used multiple authors separated by comma. In this case it becomes difficult for us to parse because we use the the comma to find the field values. Its ok to have multiple values for a field, but you have to use different delimiter like semicolon to specify multiple values of a field.  I will see if there is any better option for that.

**Comment by hdliv** [comment]
sent the new files to you

**Comment by arlin** [comment]
@abusalehmdtayeen, what language are you using?  Surely there is a pre-existing library that knows how to read and write csv files with commas in a field by enclosing the contents of the field in quotations.  This is what Excel does, for instance.  The Python csv reader will do this too, e.g., see http://stackoverflow.com/questions/8311900/python-read-csv-file-with-comma-within-fields

**Comment by abusalehmdtayeen** [comment]
@arlin, I am using python. Yes, I checked that enclosing multiple values with quotations works too. I will now use the quotations to parse then.

@Dail, thanks for sending me the new files. But I think the old ones will work too now.

**Comment by hdliv** [comment]
@arlin @abusalehmdtayeen     Please use @hdliv so that i receive notifications
